version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:13.8.0

commands:
  sayhello:
    description: "Are these manditory?"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo <<parameters.to>>

jobs:
  save_hello_world_output:
    executor: my-executor
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  hello_world_command:
    executor: my-executor
    steps:
      - sayhello

workflows:
  my_workflow:
    jobs:
      - hello_world_command