version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:13.8.0

commands:
  sayhello:
    description: "Are these manditory?"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo <<parameters.to>>
  print_pipeline_id:
    description: "Prints the pipeline id for this process"
    parameters:
      to:
        type: string
    steps:
      - run: echo <<parameters.to>>
  fail_code:
    description: "returns non-zero code"
    steps:
      - run: return 1
  success_code:
    description: "returns zero code"
    steps:
      - run: return 0

jobs:
  save_hello_world_output:
    executor: my-executor
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  hello_world_command:
    executor: my-executor
    steps:
      - sayhello
  print_pipe_id:
    executor: my-executor
    steps:
      - print_pipeline_id:
          to: "$CIRCLE_WORKFLOW_ID" 
  fail_on_purpose:
    executor: my-executor
    steps:
      - run: "echo this code fails on purpose"
      - fail_code
      - run:
          name: "Failure Report"
          command: echo "Mission Failed Successfully"
          when: on_fail
  succeed_on_purpose:
    executor: my-executor
    steps:
      - run: "echo this code succeeds on purpose"
      - success_code
      - run:
          name: "Success Report"
          command: echo "Mission Successfully Failed"
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - fail_on_purpose
      - succeed_on_purpose
        
          