---
  - name: update packages
    become: yes
    apt:
      update_cache: yes
  - name: upgrade packages
    become: yes
    apt:
      upgrade: yes
  - name: install nodejs
    become: yes
    apt:
      name: nodejs
      state: latest
  - name: install npm
    become: yes
    apt:
      name: npm
      state: latest
  - name: install pm2
    become: yes
    shell: npm install pm2 -g
  - name: create web directory at home
    file:
      path: ~/web
      state: directory
  - name: copy index
    copy:
      src: files/index.js
      dest: ~/web/index.js
  - name: start server
    shell: pm2 start ~/web/index.js -f